"""empty message

Revision ID: 84fa9588dd91
Revises: 
Create Date: 2020-08-14 21:56:56.718435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84fa9588dd91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('authorId', sa.Integer(), nullable=False),
    sa.Column('authorName', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('authorId')
    )
    op.create_index(op.f('ix_author_authorName'), 'author', ['authorName'], unique=False)
    op.create_table('fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metaId', sa.Integer(), nullable=True),
    sa.Column('arxivId', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('pdfLink', sa.String(length=128), nullable=True),
    sa.Column('abstract', sa.String(length=512), nullable=True),
    sa.Column('abstractLink', sa.String(length=128), nullable=True),
    sa.Column('authors', sa.String(length=512), nullable=True),
    sa.Column('publishedDate', sa.String(length=32), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('tag', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_abstract'), 'fact', ['abstract'], unique=False)
    op.create_index(op.f('ix_fact_abstractLink'), 'fact', ['abstractLink'], unique=False)
    op.create_index(op.f('ix_fact_arxivId'), 'fact', ['arxivId'], unique=False)
    op.create_index(op.f('ix_fact_authors'), 'fact', ['authors'], unique=False)
    op.create_index(op.f('ix_fact_link'), 'fact', ['link'], unique=False)
    op.create_index(op.f('ix_fact_metaId'), 'fact', ['metaId'], unique=False)
    op.create_index(op.f('ix_fact_pdfLink'), 'fact', ['pdfLink'], unique=False)
    op.create_index(op.f('ix_fact_publishedDate'), 'fact', ['publishedDate'], unique=False)
    op.create_index(op.f('ix_fact_tag'), 'fact', ['tag'], unique=False)
    op.create_index(op.f('ix_fact_title'), 'fact', ['title'], unique=False)
    op.create_table('freq_items',
    sa.Column('itemSetId', sa.Integer(), nullable=False),
    sa.Column('itemSet', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('itemSetId')
    )
    op.create_index(op.f('ix_freq_items_itemSet'), 'freq_items', ['itemSet'], unique=False)
    op.create_table('publication',
    sa.Column('FileId', sa.String(), nullable=False),
    sa.Column('Date', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('FileId')
    )
    op.create_index(op.f('ix_publication_Date'), 'publication', ['Date'], unique=False)
    op.create_table('topics',
    sa.Column('topicId', sa.Integer(), nullable=False),
    sa.Column('topicName', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('topicId')
    )
    op.create_index(op.f('ix_topics_topicName'), 'topics', ['topicName'], unique=False)
    op.create_table('user',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('token', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_topics_topicName'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_publication_Date'), table_name='publication')
    op.drop_table('publication')
    op.drop_index(op.f('ix_freq_items_itemSet'), table_name='freq_items')
    op.drop_table('freq_items')
    op.drop_index(op.f('ix_fact_title'), table_name='fact')
    op.drop_index(op.f('ix_fact_tag'), table_name='fact')
    op.drop_index(op.f('ix_fact_publishedDate'), table_name='fact')
    op.drop_index(op.f('ix_fact_pdfLink'), table_name='fact')
    op.drop_index(op.f('ix_fact_metaId'), table_name='fact')
    op.drop_index(op.f('ix_fact_link'), table_name='fact')
    op.drop_index(op.f('ix_fact_authors'), table_name='fact')
    op.drop_index(op.f('ix_fact_arxivId'), table_name='fact')
    op.drop_index(op.f('ix_fact_abstractLink'), table_name='fact')
    op.drop_index(op.f('ix_fact_abstract'), table_name='fact')
    op.drop_table('fact')
    op.drop_index(op.f('ix_author_authorName'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
